"""initial_schema

Revision ID: 04cb10367dfb
Revises: 
Create Date: 2026-09-07 21:50:04.055704

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('entidad', sa.String(length=80), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entidad'), 'audit_logs', ['entidad'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.create_table('customers',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('comuna', sa.String(length=120), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('users',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('sucursal', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.Enum('GERENTE_GENERAL', 'GERENTE_SUCURSAL', 'GERENTE_MARKETING', 'RESPONSABLE_MERCADO_PUBLICO', 'JEFE_SERVICIOS_TECNICOS', 'VENDEDOR', 'TECNICO', 'ADMINISTRACION', 'ADMIN_SISTEMA', name='user_role'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_telefono_whatsapp'), 'users', ['telefono_whatsapp'], unique=True)
    op.create_table('conversation_messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('machines',
    sa.Column('numero_interno', sa.String(length=20), nullable=False),
    sa.Column('numero_serie', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('horometro', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_numero_interno'), 'machines', ['numero_interno'], unique=True)
    op.create_table('pending_actions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_for_user', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'EXPIRADA', name='pending_action_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_user_id'), 'pending_actions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('asignado_a', sa.UUID(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='task_priority'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='task_status'), nullable=False),
    sa.Column('proyecto', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_asignado_a'), 'tasks', ['asignado_a'], unique=False)
    op.create_table('expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('CLP', 'USD', name='currency'), nullable=False),
    sa.Column('categoria', sa.Enum('REPUESTO', 'COMBUSTIBLE', 'PEAJE', 'ALIMENTACION', 'ALOJAMIENTO', 'TRANSPORTE', 'HERRAMIENTAS', 'INSUMOS', 'OTROS', name='expense_category'), nullable=False),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('maquina_id', sa.UUID(), nullable=True),
    sa.Column('proyecto_id', sa.UUID(), nullable=True),
    sa.Column('forma_pago', sa.Enum('TARJETA_EMPRESA', 'EFECTIVO_PROPIO', 'TRANSFERENCIA_EMPRESA', 'OTRO', name='payment_method'), nullable=False),
    sa.Column('pagado_por', sa.UUID(), nullable=True),
    sa.Column('requiere_reembolso', sa.Boolean(), nullable=False),
    sa.Column('estado_reembolso', sa.Enum('PENDIENTE', 'ENVIADO_A_CONTABILIDAD', 'APROBADO', 'PAGADO', 'RECHAZADO', name='reimbursement_status'), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maquina_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['pagado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_tasks_asignado_a'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_pending_actions_user_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_machines_numero_interno'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_users_telefono_whatsapp'), table_name='users')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_usuario_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entidad'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
