"""fase2_servicios_tecnicos_media_logs

Revision ID: 947436611085
Revises: 0001_initial_schema
Create Date: 2026-09-07 22:21:22.637619

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_fase2_servicios_tecnicos'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Secuencia para el número de orden de servicio (ej. "OT-000123"), generada en
    # app/services/service_order_service.py::_next_numero. Usar una secuencia real evita
    # colisiones si dos técnicos registran un servicio al mismo tiempo.
    op.execute("CREATE SEQUENCE service_order_number_seq START WITH 1 INCREMENT BY 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wa_media_id', sa.String(length=120), nullable=False),
    sa.Column('media_type', sa.Enum('AUDIO', 'IMAGE', 'DOCUMENT', name='media_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_logs_user_id'), 'media_logs', ['user_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('maquina_id', sa.UUID(), nullable=True),
    sa.Column('tecnico_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_llegada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_termino', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('trabajo_realizado', sa.Text(), nullable=True),
    sa.Column('repuestos_utilizados', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ASIGNADO', 'EN_RUTA', 'EN_SERVICIO', 'TERMINADO', 'CERRADO', 'CANCELADO', name='service_order_status'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['maquina_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_orders_numero'), 'service_orders', ['numero'], unique=True)
    op.create_index(op.f('ix_service_orders_tecnico_id'), 'service_orders', ['tecnico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_orders_tecnico_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_numero'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_media_logs_user_id'), table_name='media_logs')
    op.drop_table('media_logs')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE service_order_number_seq")
