"""fase3_mantenimiento

Revision ID: 166e954348e2
Revises: 0002_fase2_servicios_tecnicos
Create Date: 2026-09-07 22:53:22.759624

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_fase3_mantenimiento'
down_revision: Union[str, None] = '0002_fase2_servicios_tecnicos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('maquina_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('PREVENTIVO', 'CORRECTIVO', name='maintenance_type'), nullable=False),
    sa.Column('horometro', sa.Integer(), nullable=True),
    sa.Column('trabajos_realizados', sa.Text(), nullable=False),
    sa.Column('repuestos_utilizados', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('proximo_mantenimiento_fecha', sa.Date(), nullable=True),
    sa.Column('proximo_mantenimiento_horas', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_maquina_id'), 'maintenance_records', ['maquina_id'], unique=False)
    op.add_column('machines', sa.Column('fecha_ultimo_mantenimiento', sa.Date(), nullable=True))
    op.add_column('machines', sa.Column('fecha_proximo_mantenimiento', sa.Date(), nullable=True))
    op.add_column('machines', sa.Column('horas_proximo_mantenimiento', sa.Integer(), nullable=True))
    op.add_column('machines', sa.Column('intervalo_dias_mantenimiento', sa.Integer(), nullable=True, comment='Cada cuántos días corresponde el próximo mantenimiento, si aplica.'))
    op.add_column('machines', sa.Column('intervalo_horas_mantenimiento', sa.Integer(), nullable=True, comment='Cada cuántas horas de horómetro corresponde el próximo mantenimiento, si aplica.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'intervalo_horas_mantenimiento')
    op.drop_column('machines', 'intervalo_dias_mantenimiento')
    op.drop_column('machines', 'horas_proximo_mantenimiento')
    op.drop_column('machines', 'fecha_proximo_mantenimiento')
    op.drop_column('machines', 'fecha_ultimo_mantenimiento')
    op.drop_index(op.f('ix_maintenance_records_maquina_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
