"""fase4_vehiculos_gruas_media_storage

Revision ID: 278ee920df32
Revises: 0003_fase3_mantenimiento
Create Date: 2026-09-07 23:20:35.250923

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0004_fase4_vehiculos_gruas'
down_revision: Union[str, None] = '0003_fase3_mantenimiento'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: el tipo enum "currency" ya existe (creado en 0001_initial_schema para
    # `expenses.moneda`). Se reutiliza aquí con create_type=False para no intentar
    # recrearlo — Alembic no detecta automáticamente que ya existe entre tablas.
    currency_enum = postgresql.ENUM('CLP', 'USD', name='currency', create_type=False)
    op.create_table('crane_contracts',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('horas_contratadas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('costo_hora', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', currency_enum, nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'FINALIZADO', 'CANCELADO', name='crane_contract_status'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crane_contracts_cliente_id'), 'crane_contracts', ['cliente_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('patente', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('sucursal', sa.String(length=120), nullable=True),
    sa.Column('conductor_asignado_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conductor_asignado_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_patente'), 'vehicles', ['patente'], unique=True)
    op.create_table('crane_usage',
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas_usadas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['crane_contracts.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crane_usage_contrato_id'), 'crane_usage', ['contrato_id'], unique=False)
    op.add_column('media_logs', sa.Column('storage_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_logs', 'storage_url')
    op.drop_index(op.f('ix_crane_usage_contrato_id'), table_name='crane_usage')
    op.drop_table('crane_usage')
    op.drop_index(op.f('ix_vehicles_patente'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_crane_contracts_cliente_id'), table_name='crane_contracts')
    op.drop_table('crane_contracts')
    # ### end Alembic commands ###
